"""Content-Related Model Update

Revision ID: 0ce44b789355
Revises: a966d908fc7a
Create Date: 2026-09-17 19:50:35.037621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0ce44b789355'
down_revision: Union[str, Sequence[str], None] = 'a966d908fc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strand_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('video', 'audio', 'reading', name='content_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', 'rejected', name='content_status'), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strand_id'], ['learning_strands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('stimulus_level', sa.Enum('low', 'medium', 'high', name='stimulus_level'), nullable=False),
    sa.Column('cognitive_sustainability_rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['learning_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_item_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['strand_test_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('modules')
    op.drop_table('lessons')
    op.drop_column('learning_strands', 'created_at')
    op.drop_column('learning_strands', 'updated_at')
    op.add_column('user_profiles', sa.Column('civil_status', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'civil_status')
    op.add_column('learning_strands', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('learning_strands', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_table('lessons',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'archived', name='structure_status'), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('lessons_module_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey'))
    )
    op.create_table('modules',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'archived', name='structure_status'), autoincrement=False, nullable=True),
    sa.Column('strand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['strand_id'], ['learning_strands.id'], name=op.f('modules_strand_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('modules_pkey'))
    )
    op.drop_table('test_item_assets')
    op.drop_table('content_evaluations')
    op.drop_table('learning_contents')
    # ### end Alembic commands ###
