"""add uploaded_by attribute to contents table referencing facilitator entities

Revision ID: 5b7680c500b9
Revises: d034ea39abba
Create Date: 2026-09-25 15:32:19.158493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7680c500b9'
down_revision: Union[str, Sequence[str], None] = 'd034ea39abba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contents', 'facilitators', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'uploaded_by')
    # ### end Alembic commands ###
