"""Add Participant Intake

Revision ID: 67d662c2aef6
Revises: ec0bf05391a2
Create Date: 2026-09-18 09:08:59.215158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67d662c2aef6'
down_revision: Union[str, Sequence[str], None] = 'ec0bf05391a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_intakes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column(
    "sex",
    sa.dialects.postgresql.ENUM(
        "MALE",
        "FEMALE",
        "OTHER",
        name="gender",
        create_type=False,
    ),
    nullable=False,
    ),
    sa.Column('civil_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('highest_educational_attainment', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('als_learning_strands', sa.JSON(), nullable=False),
    sa.Column('als_enrollment_months', sa.Integer(), nullable=False),
    sa.Column('has_taken_ae_test', sa.Boolean(), nullable=False),
    sa.Column('ae_test_attempt_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_intakes')
    # ### end Alembic commands ###
