"""add visibility and uploaded at attribute to contents table, and create content_visibility enum

Revision ID: 7c1dfb597703
Revises: b065e7ba5c9f
Create Date: 2026-09-25 13:01:29.838482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c1dfb597703'
down_revision: Union[str, Sequence[str], None] = 'b065e7ba5c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE content_visibility AS ENUM ('private', 'public');")
    
    op.add_column('contents', sa.Column('visibility', sa.Enum('private', 'public', name='content_visibility'), nullable=False))
    op.add_column('contents', sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'uploaded_at')
    op.drop_column('contents', 'visibility')
    # ### end Alembic commands ###
