"""add lesson_id referencing lessons table to contents table

Revision ID: d034ea39abba
Revises: 7c1dfb597703
Create Date: 2026-09-25 15:02:39.736964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd034ea39abba'
down_revision: Union[str, Sequence[str], None] = '7c1dfb597703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('lesson_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contents', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'lesson_id')
    # ### end Alembic commands ###
